const additionalSchoolsData = [
  {
    "id": "s41",
    "name": "Школа 1502 Энергия",
    "rating": 7,
    "distance": 11.6,
    "address": "ул. Молостовых, 10А",
    "site": "https://mskobr.ru",
    "phone": "+74958811122",
    "profile": "Инженерия / ИТ",
    "medalsCount": 330,
    "graduatesCount": 480,
    "isPaid": false,
    "costPlan": 0,
    "costFact": 0,
    "status": "plan",
    "order": 40,
    "mathScore": null,
    "infoScore": null,
    "rusScore": null,
    "appointmentDate": "",
    "appointmentTime": "",
    "agreements": "",
    "timeline": []
  },
  {
    "id": "s42",
    "name": "Школа 1566 (МАРЬИНСКАЯ)",
    "rating": 12,
    "distance": 11.4,
    "address": "Люблинская ул., 173а",
    "site": "https://sch1566.mskobr.ru",
    "phone": "+7 (499) 784-88-72",
    "profile": "МАТЕМАТИКА / ИТ / КАДЕТЫ",
    "medalsCount": 310,
    "graduatesCount": 400,
    "isPaid": false,
    "costPlan": 0,
    "costFact": 0,
    "status": "plan",
    "order": 41,
    "director": "Смирнова Татьяна Викторовна",
    "buildingsCount": 15,
    "yearBuilt": 1995,
    "yearRenovated": "2024-2025 (РЕКОНСТРУКЦИЯ)",
    "equipment": "ЧПУ станки, 3D-принтеры, AI-лаборатории, Робототехника",
    "buildings": "15 зданий (8 школьных + 7 дошкольных). Основной корпус на Люблинской 173а.",
    "appointmentDate": "",
    "agreements": "",
    "timeline": []
  },
  {
    "id": "s43",
    "name": "Школа 2036",
    "rating": 18,
    "distance": 14.3,
    "address": "ул. Татьяны Макаровой, 2",
    "site": "https://mskobr.ru",
    "phone": "+74951111223",
    "profile": "ИТ вертикаль",
    "medalsCount": 220,
    "graduatesCount": 550,
    "isPaid": false,
    "costPlan": 0,
    "costFact": 0,
    "status": "plan",
    "order": 42,
    "mathScore": null,
    "infoScore": null,
    "rusScore": null,
    "appointmentDate": "",
    "appointmentTime": "",
    "agreements": "",
    "timeline": []
  },
  {
    "id": "s44",
    "name": "Школа Чуйкова",
    "rating": 28,
    "distance": 6.3,
    "address": "ул. Зеленодольская, 32",
    "site": "https://mskobr.ru",
    "phone": "+74952222233",
    "profile": "ЮВАО / Многопрофиль",
    "medalsCount": 160,
    "graduatesCount": 380,
    "isPaid": false,
    "costPlan": 0,
    "costFact": 0,
    "status": "plan",
    "order": 43,
    "mathScore": null,
    "infoScore": null,
    "rusScore": null,
    "appointmentDate": "",
    "appointmentTime": "",
    "agreements": "",
    "timeline": []
  },
  {
    "id": "s45",
    "name": "Школа 1547",
    "rating": 32,
    "distance": 9.4,
    "address": "ул. Белореченская, 47",
    "site": "https://mskobr.ru",
    "phone": "+74953333344",
    "profile": "Физика / Техно",
    "medalsCount": 185,
    "graduatesCount": 300,
    "isPaid": false,
    "costPlan": 0,
    "costFact": 0,
    "status": "plan",
    "order": 44,
    "mathScore": null,
    "infoScore": null,
    "rusScore": null,
    "appointmentDate": "",
    "appointmentTime": "",
    "agreements": "",
    "timeline": []
  },
  {
    "id": "s46",
    "name": "Европейская гимназия",
    "rating": 48,
    "distance": 8.0,
    "address": "Сокольнический Вал, 28",
    "site": "https://mskobr.ru",
    "phone": "+74954444455",
    "profile": "IB / Арт / ИТ",
    "medalsCount": 115,
    "graduatesCount": 200,
    "isPaid": true,
    "costPlan": 160000,
    "costFact": 0,
    "status": "plan",
    "order": 45,
    "mathScore": null,
    "infoScore": null,
    "rusScore": null,
    "appointmentDate": "",
    "appointmentTime": "",
    "agreements": "",
    "timeline": []
  },
  {
    "id": "s47",
    "name": "Школа Сотрудничества",
    "rating": 65,
    "distance": 3.4,
    "address": "ул. Александра Солженицына, 9А",
    "site": "https://mskobr.ru",
    "phone": "+74955555566",
    "profile": "Партнерство",
    "medalsCount": 80,
    "graduatesCount": 140,
    "isPaid": true,
    "costPlan": 145000,
    "costFact": 0,
    "status": "plan",
    "order": 46,
    "mathScore": null,
    "infoScore": null,
    "rusScore": null,
    "appointmentDate": "",
    "appointmentTime": "",
    "agreements": "",
    "timeline": []
  },
  {
    "id": "s48",
    "name": "Школа Позитив",
    "rating": 220,
    "distance": 8.1,
    "address": "Пресненская наб., 8",
    "site": "https://mskobr.ru",
    "phone": "+74956666677",
    "profile": "Цифра",
    "medalsCount": 12,
    "graduatesCount": 45,
    "isPaid": true,
    "costPlan": 120000,
    "costFact": 0,
    "status": "plan",
    "order": 47,
    "mathScore": null,
    "infoScore": null,
    "rusScore": null,
    "appointmentDate": "",
    "appointmentTime": "",
    "agreements": "",
    "timeline": []
  },
  {
    "id": "s49",
    "name": "Школа Ретро",
    "rating": 230,
    "distance": 10.4,
    "address": "ул. Мироновская, 46",
    "site": "https://mskobr.ru",
    "phone": "+74957777788",
    "profile": "Традиции",
    "medalsCount": 15,
    "graduatesCount": 50,
    "isPaid": true,
    "costPlan": 75000,
    "costFact": 0,
    "status": "plan",
    "order": 48,
    "mathScore": null,
    "infoScore": null,
    "rusScore": null,
    "appointmentDate": "",
    "appointmentTime": "",
    "agreements": "",
    "timeline": []
  },
  {
    "id": "s50",
    "name": "Лицей Москвич",
    "rating": 92,
    "distance": 4.1,
    "address": "ул. Люблинская, 15",
    "site": "https://mskobr.ru",
    "phone": "+74958888899",
    "profile": "Спорт / Учеба",
    "medalsCount": 45,
    "graduatesCount": 220,
    "isPaid": false,
    "costPlan": 0,
    "costFact": 0,
    "status": "plan",
    "order": 49,
    "mathScore": null,
    "infoScore": null,
    "rusScore": null,
    "appointmentDate": "",
    "appointmentTime": "",
    "agreements": "",
    "timeline": []
  },
  {
    "id": "s51",
    "name": "Школа 1524 (branch)",
    "rating": 98,
    "distance": 4.1,
    "address": "Гурьянова ул., 6, корп. 2",
    "site": "https://mskobr.ru",
    "phone": "+74959999900",
    "profile": "ИТ классы",
    "medalsCount": 60,
    "graduatesCount": 280,
    "isPaid": false,
    "costPlan": 0,
    "costFact": 0,
    "status": "plan",
    "order": 50,
    "mathScore": null,
    "infoScore": null,
    "rusScore": null,
    "appointmentDate": "",
    "appointmentTime": "",
    "agreements": "",
    "timeline": []
  },
  {
    "id": "s52",
    "name": "Школа 1502 (branch 2)",
    "rating": 7,
    "distance": 11.2,
    "address": "ул. Саянская, 11А",
    "site": "https://mskobr.ru",
    "phone": "+74951111234",
    "profile": "МЭИ branch",
    "medalsCount": 330,
    "graduatesCount": 200,
    "isPaid": false,
    "costPlan": 0,
    "costFact": 0,
    "status": "plan",
    "order": 51,
    "mathScore": null,
    "infoScore": null,
    "rusScore": null,
    "appointmentDate": "",
    "appointmentTime": "",
    "agreements": "",
    "timeline": []
  },
  {
    "id": "s53",
    "name": "Школа 444 (campus 2)",
    "rating": 12,
    "distance": 13.0,
    "address": "7-я Парковая ул., 1А",
    "site": "https://mskobr.ru",
    "phone": "+74952222345",
    "profile": "Мат branch",
    "medalsCount": 310,
    "graduatesCount": 150,
    "isPaid": false,
    "costPlan": 0,
    "costFact": 0,
    "status": "plan",
    "order": 52,
    "mathScore": null,
    "infoScore": null,
    "rusScore": null,
    "appointmentDate": "",
    "appointmentTime": "",
    "agreements": "",
    "timeline": []
  },
  {
    "id": "s54",
    "name": "Школа Карьера",
    "rating": 240,
    "distance": 5.4,
    "address": "Краснодонская ул., 2, корп. 4",
    "site": "https://mskobr.ru",
    "phone": "+74953333456",
    "profile": "Бизнес",
    "medalsCount": 20,
    "graduatesCount": 60,
    "isPaid": true,
    "costPlan": 85000,
    "costFact": 0,
    "status": "plan",
    "order": 53,
    "mathScore": null,
    "infoScore": null,
    "rusScore": null,
    "appointmentDate": "",
    "appointmentTime": "",
    "agreements": "",
    "timeline": []
  },
  {
    "id": "s55",
    "name": "Школа 1583",
    "rating": 52,
    "distance": 19.3,
    "address": "Флотская ул., 11",
    "site": "https://mskobr.ru",
    "phone": "+74954444567",
    "profile": "Прогресс",
    "medalsCount": 90,
    "graduatesCount": 310,
    "isPaid": false,
    "costPlan": 0,
    "costFact": 0,
    "status": "plan",
    "order": 54,
    "mathScore": null,
    "infoScore": null,
    "rusScore": null,
    "appointmentDate": "",
    "appointmentTime": "",
    "agreements": "",
    "timeline": []
  },
  {
    "id": "s56",
    "name": "Гимназия 1529",
    "rating": 37,
    "distance": 5.0,
    "address": "2-й Обыденский пер., 9",
    "site": "https://mskobr.ru",
    "phone": "+74955555678",
    "profile": "Грибоедовская",
    "medalsCount": 140,
    "graduatesCount": 400,
    "isPaid": false,
    "costPlan": 0,
    "costFact": 0,
    "status": "plan",
    "order": 55,
    "mathScore": null,
    "infoScore": null,
    "rusScore": null,
    "appointmentDate": "",
    "appointmentTime": "",
    "agreements": "",
    "timeline": []
  },
  {
    "id": "s57",
    "name": "Школа 1409",
    "rating": 21,
    "distance": 11.8,
    "address": "Ходынский бульвар, 7",
    "site": "https://mskobr.ru",
    "phone": "+74956666789",
    "profile": "Лидеры",
    "medalsCount": 200,
    "graduatesCount": 600,
    "isPaid": false,
    "costPlan": 0,
    "costFact": 0,
    "status": "plan",
    "order": 56,
    "mathScore": null,
    "infoScore": null,
    "rusScore": null,
    "appointmentDate": "",
    "appointmentTime": "",
    "agreements": "",
    "timeline": []
  },
  {
    "id": "s58",
    "name": "Школа 1568",
    "rating": 6,
    "distance": 18.3,
    "address": "пр. Шокальского, 7",
    "site": "https://mskobr.ru",
    "phone": "+74957777890",
    "profile": "Испанская / Техно",
    "medalsCount": 350,
    "graduatesCount": 380,
    "isPaid": false,
    "costPlan": 0,
    "costFact": 0,
    "status": "plan",
    "order": 57,
    "mathScore": null,
    "infoScore": null,
    "rusScore": null,
    "appointmentDate": "",
    "appointmentTime": "",
    "agreements": "",
    "timeline": []
  },
  {
    "id": "s59",
    "name": "Школа 1502 (campus 3)",
    "rating": 7,
    "distance": 17.5,
    "address": "ул. Декабристов, 8",
    "site": "https://mskobr.ru",
    "phone": "+74958888901",
    "profile": "Энергия 3",
    "medalsCount": 330,
    "graduatesCount": 250,
    "isPaid": false,
    "costPlan": 0,
    "costFact": 0,
    "status": "plan",
    "order": 58,
    "mathScore": null,
    "infoScore": null,
    "rusScore": null,
    "appointmentDate": "",
    "appointmentTime": "",
    "agreements": "",
    "timeline": []
  },
  {
    "id": "s60",
    "name": "Школа 179",
    "rating": 9,
    "distance": 6.8,
    "address": "Большая Дмитровка, 5/6",
    "site": "https://mskobr.ru",
    "phone": "+74959999012",
    "profile": "Мат вертикаль",
    "medalsCount": 350,
    "graduatesCount": 100,
    "isPaid": false,
    "costPlan": 0,
    "costFact": 0,
    "status": "plan",
    "order": 59,
    "mathScore": null,
    "infoScore": null,
    "rusScore": null,
    "appointmentDate": "",
    "appointmentTime": "",
    "agreements": "",
    "timeline": []
  }
];
const schoolsDataTotalSplit = [...initialSchoolsData, ...additionalSchoolsData];
// Добавим еще 20
const dummySchoolsGenerated = Array.from({ length: 20 }).map((_, i) => ({
  id: `s${61+i}`,
  name: `Школа №${1000+i}`,
  rating: 100 + i,
  distance: (10 + i * 0.5).toFixed(1),
  address: `Район ${i % 3}, ул. Школьная ${i}`,
  site: "https://mskobr.ru",
  phone: `+7495${Math.floor(1000000 + Math.random() * 9000000)}`,
  profile: "ИТ Профиль",
  medalsCount: 50 + i,
  graduatesCount: 200 + i,
  isPaid: false,
  costPlan: 0,
  costFact: 0,
  status: "plan",
  order: 60 + i,
  appointmentDate: "",
  appointmentTime: "",
  agreements: "",
  timeline: []
}));
window.SCHOOLS_DATABASE = [...schoolsDataTotalSplit, ...dummySchoolsGenerated];
