const initialSchoolsData = [
  {
    "id": "s1",
    "name": "Бауманская школа 1580",
    "rating": 1,
    "distance": 8.1,
    "address": "Балаклавский просп., 6А",
    "site": "https://mskobr.ru",
    "phone": "+74952743173",
    "profile": "ИТ / Физмат",
    "medalsCount": 350,
    "graduatesCount": 400,
    "isPaid": false,
    "costPlan": 0,
    "costFact": 0,
    "status": "plan",
    "order": 0,
    "mathScore": null,
    "infoScore": null,
    "rusScore": null,
    "appointmentDate": "",
    "appointmentTime": "",
    "agreements": "",
    "timeline": []
  },
  {
    "id": "s2",
    "name": "Школа 548 Царицыно",
    "rating": 13,
    "distance": 9.6,
    "address": "Каспийская ул., 30",
    "site": "https://mskobr.ru",
    "phone": "+74956123779",
    "profile": "Кванториум / ИТ",
    "medalsCount": 280,
    "graduatesCount": 500,
    "isPaid": false,
    "costPlan": 0,
    "costFact": 0,
    "status": "plan",
    "order": 1,
    "mathScore": null,
    "infoScore": null,
    "rusScore": null,
    "appointmentDate": "",
    "appointmentTime": "",
    "agreements": "",
    "timeline": []
  },
  {
    "id": "s3",
    "name": "Университетский Лицей 1511 (МИФИ)",
    "rating": 16,
    "distance": 5.6,
    "address": "Пролетарский просп., 6, корп. 3",
    "site": "https://mskobr.ru",
    "phone": "+74957404864",
    "profile": "Физика / ИТ",
    "medalsCount": 240,
    "graduatesCount": 300,
    "isPaid": false,
    "costPlan": 0,
    "costFact": 0,
    "status": "plan",
    "order": 2,
    "mathScore": null,
    "infoScore": null,
    "rusScore": null,
    "appointmentDate": "",
    "appointmentTime": "",
    "agreements": "",
    "timeline": []
  },
  {
    "id": "s4",
    "name": "Лицей 1533 (ЛИТ)",
    "rating": 20,
    "distance": 7.0,
    "address": "Ломоносовский просп., 16",
    "site": "https://mskobr.ru",
    "phone": "+74954070359",
    "profile": "Программирование",
    "medalsCount": 220,
    "graduatesCount": 250,
    "isPaid": false,
    "costPlan": 0,
    "costFact": 0,
    "status": "plan",
    "order": 3,
    "mathScore": null,
    "infoScore": null,
    "rusScore": null,
    "appointmentDate": "",
    "appointmentTime": "",
    "agreements": "",
    "timeline": []
  },
  {
    "id": "s5",
    "name": "Лицей «Вторая школа»",
    "rating": 3,
    "distance": 5.8,
    "address": "ул. Фотиевой, 18",
    "site": "https://mskobr.ru",
    "phone": "+74957332368",
    "profile": "Математика / ИТ",
    "medalsCount": 450,
    "graduatesCount": 200,
    "isPaid": false,
    "costPlan": 0,
    "costFact": 0,
    "status": "plan",
    "order": 4,
    "mathScore": null,
    "infoScore": null,
    "rusScore": null,
    "appointmentDate": "",
    "appointmentTime": "",
    "agreements": "",
    "timeline": []
  },
  {
    "id": "s6",
    "name": "Школа 1543",
    "rating": 10,
    "distance": 12.8,
    "address": "ул. 26 Бакинских Комиссаров, 3, корп. 5",
    "site": "https://mskobr.ru",
    "phone": "+74951182045",
    "profile": "Биохим / Мат",
    "medalsCount": 180,
    "graduatesCount": 150,
    "isPaid": false,
    "costPlan": 0,
    "costFact": 0,
    "status": "plan",
    "order": 5,
    "mathScore": null,
    "infoScore": null,
    "rusScore": null,
    "appointmentDate": "",
    "appointmentTime": "",
    "agreements": "",
    "timeline": []
  },
  {
    "id": "s7",
    "name": "Школа 1514",
    "rating": 5,
    "distance": 8.4,
    "address": "ул. Крупской, 12",
    "site": "https://mskobr.ru",
    "phone": "+74957399771",
    "profile": "Математика / Гум",
    "medalsCount": 310,
    "graduatesCount": 350,
    "isPaid": false,
    "costPlan": 0,
    "costFact": 0,
    "status": "plan",
    "order": 6,
    "mathScore": null,
    "infoScore": null,
    "rusScore": null,
    "appointmentDate": "",
    "appointmentTime": "",
    "agreements": "",
    "timeline": []
  },
  {
    "id": "s8",
    "name": "Школа 2086",
    "rating": 25,
    "distance": 7.3,
    "address": "Университетский просп., 7",
    "site": "https://mskobr.ru",
    "phone": "+74955759943",
    "profile": "ИТ / Многопрофиль",
    "medalsCount": 150,
    "graduatesCount": 280,
    "isPaid": false,
    "costPlan": 0,
    "costFact": 0,
    "status": "plan",
    "order": 7,
    "mathScore": null,
    "infoScore": null,
    "rusScore": null,
    "appointmentDate": "",
    "appointmentTime": "",
    "agreements": "",
    "timeline": []
  },
  {
    "id": "s9",
    "name": "Школа 1535 (main)",
    "rating": 2,
    "distance": 6.8,
    "address": "ул. Усачева, 50",
    "site": "https://mskobr.ru",
    "phone": "+74959995802",
    "profile": "Медицина / ИТ",
    "medalsCount": 420,
    "graduatesCount": 500,
    "isPaid": false,
    "costPlan": 0,
    "costFact": 0,
    "status": "plan",
    "order": 8,
    "mathScore": null,
    "infoScore": null,
    "rusScore": null,
    "appointmentDate": "",
    "appointmentTime": "",
    "agreements": "",
    "timeline": []
  },
  {
    "id": "s10",
    "name": "Школа 1158",
    "rating": 45,
    "distance": 8.6,
    "address": "мкр. Сев. Чертаново, к809",
    "site": "https://mskobr.ru",
    "phone": "+74953487526",
    "profile": "ИТ классы",
    "medalsCount": 90,
    "graduatesCount": 420,
    "isPaid": false,
    "costPlan": 0,
    "costFact": 0,
    "status": "plan",
    "order": 9,
    "mathScore": null,
    "infoScore": null,
    "rusScore": null,
    "appointmentDate": "",
    "appointmentTime": "",
    "agreements": "",
    "timeline": []
  },
  {
    "id": "s11",
    "name": "Школа 1034",
    "rating": 80,
    "distance": 11.0,
    "address": "ул. Алма-Атинская, 9, корп. 3",
    "site": "https://mskobr.ru",
    "phone": "+74952522375",
    "profile": "ИТ вертикаль",
    "medalsCount": 60,
    "graduatesCount": 310,
    "isPaid": false,
    "costPlan": 0,
    "costFact": 0,
    "status": "plan",
    "order": 10,
    "mathScore": null,
    "infoScore": null,
    "rusScore": null,
    "appointmentDate": "",
    "appointmentTime": "",
    "agreements": "",
    "timeline": []
  },
  {
    "id": "s12",
    "name": "Наследник (Частная)",
    "rating": 105,
    "distance": 8.8,
    "address": "ул. Борисовские Пруды, 13, корп. 4",
    "site": "https://mskobr.ru",
    "phone": "+74958072735",
    "profile": "ИТ / Бизнес",
    "medalsCount": 120,
    "graduatesCount": 180,
    "isPaid": true,
    "costPlan": 120000,
    "costFact": 0,
    "status": "plan",
    "order": 11,
    "mathScore": null,
    "infoScore": null,
    "rusScore": null,
    "appointmentDate": "",
    "appointmentTime": "",
    "agreements": "",
    "timeline": []
  },
  {
    "id": "s13",
    "name": "Взмах (Частная)",
    "rating": 110,
    "distance": 7.9,
    "address": "ул. Архитектора Власова, 7, корп. 3",
    "site": "https://mskobr.ru",
    "phone": "+74954315546",
    "profile": "Бизнес / ИТ",
    "medalsCount": 85,
    "graduatesCount": 120,
    "isPaid": true,
    "costPlan": 85000,
    "costFact": 0,
    "status": "plan",
    "order": 12,
    "mathScore": null,
    "infoScore": null,
    "rusScore": null,
    "appointmentDate": "",
    "appointmentTime": "",
    "agreements": "",
    "timeline": []
  },
  {
    "id": "s14",
    "name": "TOP IT School ЮЗАО",
    "rating": 120,
    "distance": 11.3,
    "address": "ул. Миклухо-Маклая, 11",
    "site": "https://mskobr.ru",
    "phone": "+74957120505",
    "profile": "Программирование",
    "medalsCount": 40,
    "graduatesCount": 60,
    "isPaid": true,
    "costPlan": 79000,
    "costFact": 0,
    "status": "plan",
    "order": 13,
    "mathScore": null,
    "infoScore": null,
    "rusScore": null,
    "appointmentDate": "",
    "appointmentTime": "",
    "agreements": "",
    "timeline": []
  },
  {
    "id": "s15",
    "name": "Школа 1279",
    "rating": 70,
    "distance": 5.9,
    "address": "Азовская ул., 2, корп. 2",
    "site": "https://mskobr.ru",
    "phone": "+74955747281",
    "profile": "Профиль",
    "medalsCount": 75,
    "graduatesCount": 240,
    "isPaid": false,
    "costPlan": 0,
    "costFact": 0,
    "status": "plan",
    "order": 14,
    "mathScore": null,
    "infoScore": null,
    "rusScore": null,
    "appointmentDate": "",
    "appointmentTime": "",
    "agreements": "",
    "timeline": []
  },
  {
    "id": "s16",
    "name": "Ковчег-XXI (branch)",
    "rating": 130,
    "distance": 10.0,
    "address": "ул. Обручева, 5А",
    "site": "https://mskobr.ru",
    "phone": "+74955331682",
    "profile": "Индивидуал",
    "medalsCount": 30,
    "graduatesCount": 45,
    "isPaid": true,
    "costPlan": 95000,
    "costFact": 0,
    "status": "plan",
    "order": 15,
    "mathScore": null,
    "infoScore": null,
    "rusScore": null,
    "appointmentDate": "",
    "appointmentTime": "",
    "agreements": "",
    "timeline": []
  },
  {
    "id": "s17",
    "name": "Школа Ника",
    "rating": 140,
    "distance": 9.0,
    "address": "ул. Академика Пилюгина, 14, корп. 2",
    "site": "https://mskobr.ru",
    "phone": "+74954428952",
    "profile": "Прогресс",
    "medalsCount": 50,
    "graduatesCount": 80,
    "isPaid": true,
    "costPlan": 110000,
    "costFact": 0,
    "status": "plan",
    "order": 16,
    "mathScore": null,
    "infoScore": null,
    "rusScore": null,
    "appointmentDate": "",
    "appointmentTime": "",
    "agreements": "",
    "timeline": []
  },
  {
    "id": "s18",
    "name": "Discovery Junior",
    "rating": 150,
    "distance": 8.1,
    "address": "Ленинский просп., 83",
    "site": "https://mskobr.ru",
    "phone": "+74956451815",
    "profile": "Bilingual / IT",
    "medalsCount": 20,
    "graduatesCount": 30,
    "isPaid": true,
    "costPlan": 150000,
    "costFact": 0,
    "status": "plan",
    "order": 17,
    "mathScore": null,
    "infoScore": null,
    "rusScore": null,
    "appointmentDate": "",
    "appointmentTime": "",
    "agreements": "",
    "timeline": []
  },
  {
    "id": "s19",
    "name": "Школа 1526",
    "rating": 85,
    "distance": 10.1,
    "address": "Дорожная ул., 20А",
    "site": "https://mskobr.ru",
    "phone": "+74952624958",
    "profile": "Инженерия",
    "medalsCount": 65,
    "graduatesCount": 320,
    "isPaid": false,
    "costPlan": 0,
    "costFact": 0,
    "status": "plan",
    "order": 18,
    "mathScore": null,
    "infoScore": null,
    "rusScore": null,
    "appointmentDate": "",
    "appointmentTime": "",
    "agreements": "",
    "timeline": []
  },
  {
    "id": "s20",
    "name": "Школа 1259",
    "rating": 55,
    "distance": 3.2,
    "address": "5-й Монетчиковский пер., 7",
    "site": "https://mskobr.ru",
    "phone": "+74953562573",
    "profile": "Многопрофиль",
    "medalsCount": 110,
    "graduatesCount": 180,
    "isPaid": false,
    "costPlan": 0,
    "costFact": 0,
    "status": "plan",
    "order": 19,
    "mathScore": null,
    "infoScore": null,
    "rusScore": null,
    "appointmentDate": "",
    "appointmentTime": "",
    "agreements": "",
    "timeline": []
  },
  {
    "id": "s21",
    "name": "Школа 1329",
    "rating": 8,
    "distance": 13.6,
    "address": "ул. Никулинская, 10",
    "site": "https://mskobr.ru",
    "phone": "+74959194949",
    "profile": "ИТ / Роботы",
    "medalsCount": 380,
    "graduatesCount": 450,
    "isPaid": false,
    "costPlan": 0,
    "costFact": 0,
    "status": "plan",
    "order": 20,
    "mathScore": null,
    "infoScore": null,
    "rusScore": null,
    "appointmentDate": "",
    "appointmentTime": "",
    "agreements": "",
    "timeline": []
  },
  {
    "id": "s22",
    "name": "Школа Летово",
    "rating": 4,
    "distance": 22.0,
    "address": "пос. Сосенское, ул. Зименковская, 3",
    "site": "https://mskobr.ru",
    "phone": "+74952609873",
    "profile": "IB / ИТ",
    "medalsCount": 500,
    "graduatesCount": 600,
    "isPaid": true,
    "costPlan": 150000,
    "costFact": 0,
    "status": "plan",
    "order": 21,
    "mathScore": null,
    "infoScore": null,
    "rusScore": null,
    "appointmentDate": "",
    "appointmentTime": "",
    "agreements": "",
    "timeline": []
  },
  {
    "id": "s23",
    "name": "Школа Интеллектуал",
    "rating": 11,
    "distance": 14.0,
    "address": "ул. Тихомирова, 6",
    "site": "https://mskobr.ru",
    "phone": "+74956171344",
    "profile": "Проектная",
    "medalsCount": 190,
    "graduatesCount": 80,
    "isPaid": false,
    "costPlan": 0,
    "costFact": 0,
    "status": "plan",
    "order": 22,
    "mathScore": null,
    "infoScore": null,
    "rusScore": null,
    "appointmentDate": "",
    "appointmentTime": "",
    "agreements": "",
    "timeline": []
  },
  {
    "id": "s24",
    "name": "Школа 1567",
    "rating": 15,
    "distance": 8.9,
    "address": "наб. Тараса Шевченко, 23",
    "site": "https://mskobr.ru",
    "phone": "+74958407090",
    "profile": "Физмат",
    "medalsCount": 210,
    "graduatesCount": 200,
    "isPaid": false,
    "costPlan": 0,
    "costFact": 0,
    "status": "plan",
    "order": 23,
    "mathScore": null,
    "infoScore": null,
    "rusScore": null,
    "appointmentDate": "",
    "appointmentTime": "",
    "agreements": "",
    "timeline": []
  },
  {
    "id": "s25",
    "name": "Школа 1253",
    "rating": 40,
    "distance": 5.5,
    "address": "ул. Льва Толстого, 16",
    "site": "https://mskobr.ru",
    "phone": "+74951776653",
    "profile": "Лингвистика / ИТ",
    "medalsCount": 100,
    "graduatesCount": 250,
    "isPaid": false,
    "costPlan": 0,
    "costFact": 0,
    "status": "plan",
    "order": 24,
    "mathScore": null,
    "infoScore": null,
    "rusScore": null,
    "appointmentDate": "",
    "appointmentTime": "",
    "agreements": "",
    "timeline": []
  },
  {
    "id": "s26",
    "name": "Хорошкола",
    "rating": 50,
    "distance": 13.8,
    "address": "ул. Народного Ополчения, 9А",
    "site": "https://mskobr.ru",
    "phone": "+74951535540",
    "profile": "Soft Skills / IT",
    "medalsCount": 120,
    "graduatesCount": 300,
    "isPaid": true,
    "costPlan": 137000,
    "costFact": 0,
    "status": "plan",
    "order": 25,
    "mathScore": null,
    "infoScore": null,
    "rusScore": null,
    "appointmentDate": "",
    "appointmentTime": "",
    "agreements": "",
    "timeline": []
  },
  {
    "id": "s27",
    "name": "Новая школа",
    "rating": 60,
    "distance": 10.0,
    "address": "ул. Мосфильмовская, 88, корп. 5",
    "site": "https://mskobr.ru",
    "phone": "+74955255554",
    "profile": "Академическая",
    "medalsCount": 140,
    "graduatesCount": 280,
    "isPaid": true,
    "costPlan": 100000,
    "costFact": 0,
    "status": "plan",
    "order": 26,
    "mathScore": null,
    "infoScore": null,
    "rusScore": null,
    "appointmentDate": "",
    "appointmentTime": "",
    "agreements": "",
    "timeline": []
  },
  {
    "id": "s28",
    "name": "МЭШ",
    "rating": 75,
    "distance": 24.6,
    "address": "Зайцево, д. 1",
    "site": "https://mskobr.ru",
    "phone": "+74951235678",
    "profile": "Международная",
    "medalsCount": 110,
    "graduatesCount": 200,
    "isPaid": true,
    "costPlan": 180000,
    "costFact": 0,
    "status": "plan",
    "order": 27,
    "mathScore": null,
    "infoScore": null,
    "rusScore": null,
    "appointmentDate": "",
    "appointmentTime": "",
    "agreements": "",
    "timeline": []
  },
  {
    "id": "s29",
    "name": "Гимназия Сколково",
    "rating": 42,
    "distance": 19.7,
    "address": "ул. Зворыкина, 4",
    "site": "https://mskobr.ru",
    "phone": "+74957891663",
    "profile": "High-Tech",
    "medalsCount": 95,
    "graduatesCount": 150,
    "isPaid": true,
    "costPlan": 120000,
    "costFact": 0,
    "status": "plan",
    "order": 28,
    "mathScore": null,
    "infoScore": null,
    "rusScore": null,
    "appointmentDate": "",
    "appointmentTime": "",
    "agreements": "",
    "timeline": []
  },
  {
    "id": "s30",
    "name": "Примакова (branch)",
    "rating": 22,
    "distance": 23.1,
    "address": "Раздоры, д. 1",
    "site": "https://mskobr.ru",
    "phone": "+74953381122",
    "profile": "Лидерство",
    "medalsCount": 180,
    "graduatesCount": 250,
    "isPaid": true,
    "costPlan": 150000,
    "costFact": 0,
    "status": "plan",
    "order": 29,
    "mathScore": null,
    "infoScore": null,
    "rusScore": null,
    "appointmentDate": "",
    "appointmentTime": "",
    "agreements": "",
    "timeline": []
  },
  {
    "id": "s31",
    "name": "Павловская гимназия",
    "rating": 35,
    "distance": 34.4,
    "address": "Веледниково, 1",
    "site": "https://mskobr.ru",
    "phone": "+74957210670",
    "profile": "Элитарная",
    "medalsCount": 70,
    "graduatesCount": 100,
    "isPaid": true,
    "costPlan": 200000,
    "costFact": 0,
    "status": "plan",
    "order": 30,
    "mathScore": null,
    "infoScore": null,
    "rusScore": null,
    "appointmentDate": "",
    "appointmentTime": "",
    "agreements": "",
    "timeline": []
  },
  {
    "id": "s32",
    "name": "Классическое образование",
    "rating": 90,
    "distance": 11.0,
    "address": "ул. Староволынская, 12, корп. 5",
    "site": "https://mskobr.ru",
    "phone": "+74953835822",
    "profile": "Классика",
    "medalsCount": 55,
    "graduatesCount": 140,
    "isPaid": true,
    "costPlan": 75000,
    "costFact": 0,
    "status": "plan",
    "order": 31,
    "mathScore": null,
    "infoScore": null,
    "rusScore": null,
    "appointmentDate": "",
    "appointmentTime": "",
    "agreements": "",
    "timeline": []
  },
  {
    "id": "s33",
    "name": "Олимп-Плюс",
    "rating": 95,
    "distance": 12.3,
    "address": "ул. Удальцова, 67",
    "site": "https://mskobr.ru",
    "phone": "+74951848331",
    "profile": "Инновации",
    "medalsCount": 65,
    "graduatesCount": 120,
    "isPaid": true,
    "costPlan": 82000,
    "costFact": 0,
    "status": "plan",
    "order": 32,
    "mathScore": null,
    "infoScore": null,
    "rusScore": null,
    "appointmentDate": "",
    "appointmentTime": "",
    "agreements": "",
    "timeline": []
  },
  {
    "id": "s34",
    "name": "Heritage International",
    "rating": 160,
    "distance": 9.1,
    "address": "ул. 2-я Звенигородская, 12",
    "site": "https://mskobr.ru",
    "phone": "+74953331122",
    "profile": "English",
    "medalsCount": 30,
    "graduatesCount": 50,
    "isPaid": true,
    "costPlan": 200000,
    "costFact": 0,
    "status": "plan",
    "order": 33,
    "mathScore": null,
    "infoScore": null,
    "rusScore": null,
    "appointmentDate": "",
    "appointmentTime": "",
    "agreements": "",
    "timeline": []
  },
  {
    "id": "s35",
    "name": "Президентская школа",
    "rating": 102,
    "distance": 10.4,
    "address": "Фили-Давыдково",
    "site": "https://mskobr.ru",
    "phone": "+74956711122",
    "profile": "Бизнес",
    "medalsCount": 60,
    "graduatesCount": 100,
    "isPaid": true,
    "costPlan": 135000,
    "costFact": 0,
    "status": "plan",
    "order": 34,
    "mathScore": null,
    "infoScore": null,
    "rusScore": null,
    "appointmentDate": "",
    "appointmentTime": "",
    "agreements": "",
    "timeline": []
  },
  {
    "id": "s36",
    "name": "Школа Путь к успеху",
    "rating": 170,
    "distance": 13.9,
    "address": "ул. Маршала Тимошенко, 17",
    "site": "https://mskobr.ru",
    "phone": "+74952211122",
    "profile": "Саморазвитие",
    "medalsCount": 25,
    "graduatesCount": 40,
    "isPaid": true,
    "costPlan": 95000,
    "costFact": 0,
    "status": "plan",
    "order": 35,
    "mathScore": null,
    "infoScore": null,
    "rusScore": null,
    "appointmentDate": "",
    "appointmentTime": "",
    "agreements": "",
    "timeline": []
  },
  {
    "id": "s37",
    "name": "Лицей Ступени",
    "rating": 180,
    "distance": 12.3,
    "address": "ул. Ращупкина, 15",
    "site": "https://mskobr.ru",
    "phone": "+74953344422",
    "profile": "Домашняя",
    "medalsCount": 15,
    "graduatesCount": 60,
    "isPaid": true,
    "costPlan": 70000,
    "costFact": 0,
    "status": "plan",
    "order": 36,
    "mathScore": null,
    "infoScore": null,
    "rusScore": null,
    "appointmentDate": "",
    "appointmentTime": "",
    "agreements": "",
    "timeline": []
  },
  {
    "id": "s38",
    "name": "Школа Лидер",
    "rating": 190,
    "distance": 9.6,
    "address": "ул. Лобачевского, 92",
    "site": "https://mskobr.ru",
    "phone": "+74955511122",
    "profile": "Успех",
    "medalsCount": 20,
    "graduatesCount": 55,
    "isPaid": true,
    "costPlan": 110000,
    "costFact": 0,
    "status": "plan",
    "order": 37,
    "mathScore": null,
    "infoScore": null,
    "rusScore": null,
    "appointmentDate": "",
    "appointmentTime": "",
    "agreements": "",
    "timeline": []
  },
  {
    "id": "s39",
    "name": "Мир Знаний",
    "rating": 200,
    "distance": 11.2,
    "address": "ул. Островная, 2",
    "site": "https://mskobr.ru",
    "phone": "+74956611122",
    "profile": "Актив",
    "medalsCount": 10,
    "graduatesCount": 40,
    "isPaid": true,
    "costPlan": 85000,
    "costFact": 0,
    "status": "plan",
    "order": 38,
    "mathScore": null,
    "infoScore": null,
    "rusScore": null,
    "appointmentDate": "",
    "appointmentTime": "",
    "agreements": "",
    "timeline": []
  },
  {
    "id": "s40",
    "name": "Остеон",
    "rating": 210,
    "distance": 11.2,
    "address": "ул. Верейская, 29",
    "site": "https://mskobr.ru",
    "phone": "+74957711122",
    "profile": "Баланс",
    "medalsCount": 8,
    "graduatesCount": 30,
    "isPaid": true,
    "costPlan": 90000,
    "costFact": 0,
    "status": "plan",
    "order": 39,
    "mathScore": null,
    "infoScore": null,
    "rusScore": null,
    "appointmentDate": "",
    "appointmentTime": "",
    "agreements": "",
    "timeline": []
  }
];
